In [1]:
import pandas as pd

In [2]:
ss = pd.read_csv("../data/raw/synthetic_squarespace_sales_2024_WEIGHTED.csv")

In [3]:
ss.head()

,order_id,order_date,product_name,quantity,unit_price,gross_sales,discount_amount,refund_amount,net_sales,state
0,SS3000,2024-01-01,My Hero Academia Backpack,1,48,48,0.00,0.0,48.00,Florida
1,SS3001,2024-01-01,One Piece Figure,1,35,35,6.42,0.0,28.58,Illinois
2,SS3002,2024-01-01,Attack on Titan T-Shirt,1,28,28,0.00,0.0,28.00,Texas
3,SS3003,2024-01-01,Anime Mystery Box,1,60,60,6.16,0.0,53.84,Massachusetts
4,SS3004,2024-01-01,Anime Mystery Box,1,60,60,0.00,0.0,60.00,California

In [ ]:
 ss[ss["state"].isin(["Texas","California", "Florida"])]

,order_id,order_date,product_name,quantity,unit_price,gross_sales,discount_amount,refund_amount,net_sales,state
0,SS3000,2024-01-01,My Hero Academia Backpack,1,48,48,0.00,0.0,48.00,Florida
2,SS3002,2024-01-01,Attack on Titan T-Shirt,1,28,28,0.00,0.0,28.00,Texas
4,SS3004,2024-01-01,Anime Mystery Box,1,60,60,0.00,0.0,60.00,California
5,SS3005,2024-01-01,Anime Mystery Box,3,60,180,28.06,0.0,151.94,Texas
6,SS3006,2024-01-01,Anime Mystery Box,1,60,60,0.00,0.0,60.00,California
...,...,...,...,...,...,...,...,...,...,...
4411,SS7411,2024-12-30,My Hero Academia Backpack,2,48,96,0.00,0.0,96.00,Texas
4412,SS7412,2024-12-31,Demon Slayer Poster,1,15,15,0.00,0.0,15.00,Florida
4413,SS7413,2024-12-31,My Hero Academia Backpack,3,48,144,0.00,0.0,144.00,Texas
4414,SS7414,2024-12-31,Anime Mystery Box,1,60,60,0.00,0.0,60.00,Florida
4417,SS7417,2024-12-31,Anime Mystery Box,2,60,120,0.00,0.0,120.00,Florida

In [5]:
ss[ss["state"].isin(["Texas","California", "Florida"])].groupby(["state", "product_name"])

In [6]:
ss[ss["state"].isin(["Texas","California", "Florida"])]["gross_sales"].sum()

np.int64(233641)